"""Initial migration with comments and wireframes

Revision ID: 603ae629a5ec
Revises: 
Create Date: 2025-07-14 17:20:09.891038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603ae629a5ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wireframes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('page_name', sa.String(), nullable=True),
    sa.Column('page_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wireframes_id'), 'wireframes', ['id'], unique=False)
    op.create_index(op.f('ix_wireframes_project'), 'wireframes', ['project'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('page_name', sa.String(), nullable=True),
    sa.Column('page_path', sa.String(), nullable=True),
    sa.Column('ui_component', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('wireframe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wireframe_id'], ['wireframes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_wireframes_project'), table_name='wireframes')
    op.drop_index(op.f('ix_wireframes_id'), table_name='wireframes')
    op.drop_table('wireframes')
    # ### end Alembic commands ###
